version: '2'
services:

  rabbit:
    image: rabbitmq:3.6.5-management
    volumes:
      - ./config/rabbit/definitions.json:/opt/definitions.json:ro
      - ./config/rabbit/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
    ports:
      - "15672:15672"
      - "5672:5672"

  cv_api:
    image: cv_api
    ports:
      - "8080:8080"
    build:
      context: ./cv-api
    volumes:
      - ./cv-api:/app

  beego_app:
    image: beego_app
    ports:
      - "8082:8080"
    build:
      context: ./beego-app
    volumes:
      - .:/go/src/github.com/wwgberlin/bubble
    depends_on:
      - rabbit
    links:
      - rabbit